tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#D0AC6E",
        "on-tertiary": "#303030",
        "on-surface-variant": "#B8D4C0",
        "outline": "#5A7A64",
        "inverse-on-surface": "#1C3529",
        "secondary-fixed": "#feddb8",
        "on-surface": "#F5F0E8",
        "tertiary-fixed-dim": "#c7c6c6",
        "outline-variant": "#2D4A38",
        "on-primary": "#680010",
        "surface-dim": "#0D1A13",
        "secondary-fixed-dim": "#e1c19e",
        "on-secondary-fixed": "#291803",
        "on-background": "#F5F0E8",
        "tertiary": "#c7c6c6",
        "primary-fixed-dim": "#ffb3b0",
        "on-primary-fixed-variant": "#92001b",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#410007",
        "on-tertiary-fixed": "#1b1c1c",
        "secondary": "#e1c19e",
        "surface-bright": "#2D4A38",
        "on-secondary-container": "#cfb08e",
        "secondary-container": "#594328",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#594328",
        "surface-tint": "#ffb3b0",
        "background": "#0D1A13",
        "error": "#ffb4ab",
        "on-tertiary-container": "#ffffff",
        "on-primary-container": "#1C3529",
        "tertiary-fixed": "#e4e2e2",
        "surface-container-highest": "#2D4A38",
        "tertiary-container": "#767676",
        "surface-variant": "#2D4A38",
        "on-secondary": "#402d14",
        "surface": "#0D1A13",
        "surface-container-high": "#243D2F",
        "surface-container-lowest": "#0A1510",
        "primary-fixed": "#ffdad8",
        "error-container": "#93000a",
        "surface-container": "#1C3529",
        "primary": "#ffb3b0",
        "inverse-surface": "#F5F0E8",
        "inverse-primary": "#8B6A35",
        "surface-container-low": "#121E17",
        "on-tertiary-fixed-variant": "#464747"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
}